user_index:
    path:     /all
    defaults: { _controller: "SecurityAppBundle:User:index" }
    methods:  GET
    host: "%casemanager_admin_url%"

user_show:
    path:     /{slug}/show
    defaults: { _controller: "SecurityAppBundle:User:show" }
    methods:  GET

user_new:
    path:     /new
    defaults: { _controller: "SecurityAppBundle:User:new" }
    methods:  [GET, POST]
    host: "%casemanager_admin_url%"

user_edit:
    path:     /{slug}/edit
    defaults: { _controller: "SecurityAppBundle:User:edit" }
    methods:  [GET, POST]
    host: "%casemanager_admin_url%"

user_delete:
    path:     /{slug}/delete
    defaults: { _controller: "SecurityAppBundle:User:delete" }
    methods:  DELETE
    host: "%casemanager_admin_url%"
    
user_export:
    path: /export/{slug}
    defaults: { _controller: "SecurityAppBundle:User:exportUser" }

user_export_all:
    path: /export
    defaults: { _controller: "SecurityAppBundle:User:exportAllUser" }