admin_homepage:
    path:     /
    defaults: { _controller: AdminBundle:Default:index }
    host: "%casemanager_admin_url%"

admin_work_site_type:
    resource: "@AdminBundle/Resources/config/routing/prestation.yml"
    prefix: /prestation
#    host: "%casemanager_admin_url%"

admin_rate:
    resource: "@AdminBundle/Resources/config/routing/rate.yml"
    prefix: /rate
#    host: "%casemanager_admin_url%"