<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\MediaBundle\Entity;

use Sonata\MediaBundle\Entity\BaseMedia as BaseMedia;

/**
 * This file has been generated by the Sonata EasyExtends bundle.
 *
 * @link https://sonata-project.org/bundles/easy-extends
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class BusinessCaseMedia extends BaseMedia
{
    /**
     * @var int $id
     */
    protected $id;

    /**
     * @var \BusinessBundle\Entity\BusinessCaseGallery
     */
    protected $businessCaseGallery;

    /**
     * Get id
     *
     * @return int $id
     */
    public function getId()
    {
        return $this->id;
    }

    public function setBinaryContent( $binaryContent )
    {
        if(!$this->providerReference && $this->previousProviderReference){
            $this->providerReference = $this->previousProviderReference;
        }
        //  $this->providerReference = null;
        $this->binaryContent = $binaryContent;
    }

    public function getBase64Image(){

    }

    /**
     * @return \BusinessBundle\Entity\BusinessCaseGallery
     */
    public function getBusinessCaseGallery(): \BusinessBundle\Entity\BusinessCaseGallery
    {
        return $this->businessCaseGallery;
    }

    /**
     * @param \BusinessBundle\Entity\BusinessCaseGallery $businessCaseGallery
     */
    public function setBusinessCaseGallery(\BusinessBundle\Entity\BusinessCaseGallery $businessCaseGallery)
    {
        $this->businessCaseGallery = $businessCaseGallery;
    }

}
