imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@AdminBundle/Resources/config/services.yml" }
    - { resource: "@CustomerBundle/Resources/config/services.yml" }
    - { resource: "@BusinessBundle/Resources/config/services.yml" }
    - { resource: "@ApplicationSonataMediaBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true
    translator: { fallbacks: [en] }

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_theme:
        - 'form/common_form_rules.html.twig'
#        - 'bootstrap_3_horizontal_layout.html.twig'
services:
    gedmo.listener.tree:
        class: Gedmo\Tree\TreeListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ '@annotation_reader' ] ]

    gedmo.listener.translatable:
        class: Gedmo\Translatable\TranslatableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ '@annotation_reader' ] ]
            - [ setDefaultLocale, [ '%locale%' ] ]
            - [ setTranslationFallback, [ false ] ]

    gedmo.listener.timestampable:
        class: Gedmo\Timestampable\TimestampableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ '@annotation_reader' ] ]

    gedmo.listener.sluggable:
        class: Gedmo\Sluggable\SluggableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ '@annotation_reader' ] ]

    gedmo.listener.sortable:
        class: Gedmo\Sortable\SortableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ '@annotation_reader' ] ]

    twig.extension.text:
       class: Twig_Extensions_Extension_Text
       tags:
            - { name: twig.extension }

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    app.twig.extension.country_extension:
        class: AppBundle\Twig\Extension\CountryExtension
        tags:
            - { name: twig.extension }

    app.twig.extension.word_extension:
        class: AppBundle\Twig\Extension\WordExtension
        tags:
            - { name: twig.extension }

    app.twig.extension.translation_extension:
        class: AppBundle\Twig\Extension\TranslationExtension
        tags:
            - { name: twig.extension }
        arguments:
            - "@translator"

genemu_form:
    tinymce:
        enabled: true
        theme: modern
        configs:
            entity_encoding: raw
            plugins : 'advlist autolink link image lists charmap print preview'
        script_url: 'vendor/tinymce/tinymce.min.js'
    date: ~
    image: ~
    select2:
        enabled: true
        configs:
            placeholder: Chose
            width: off
            allowClear: false
            minimumInputLength: 0
# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        server_version: 5.6
        types:
            json: Sonata\Doctrine\Types\JsonType
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                mappings:
                    #ApplicationSonataMediaBundle: ~
                    SonataMediaBundle: ~
                    AppBundle: ~
                    SecurityAppBundle: ~
                dql:
                    datetime_functions:
                        convert_tz: DoctrineExtensions\Query\Mysql\ConvertTz
                        date: DoctrineExtensions\Query\Mysql\Date
                        date_format: DoctrineExtensions\Query\Mysql\DateFormat
                        dateadd: DoctrineExtensions\Query\Mysql\DateAdd
                        datesub: DoctrineExtensions\Query\Mysql\DateSub
                        datediff: DoctrineExtensions\Query\Mysql\DateDiff
                        day: DoctrineExtensions\Query\Mysql\Day
                        dayname: DoctrineExtensions\Query\Mysql\DayName
                        dayofweek: DoctrineExtensions\Query\Mysql\DayOfWeek
                        dayofyear: DoctrineExtensions\Query\Mysql\DayOfYear
                        div: DoctrineExtensions\Query\Mysql\Div
                        from_unixtime: DoctrineExtensions\Query\Mysql\FromUnixtime
                        hour: DoctrineExtensions\Query\Mysql\Hour
                        last_day: DoctrineExtensions\Query\Mysql\LastDay
                        minute: DoctrineExtensions\Query\Mysql\Minute
                        now: DoctrineExtensions\Query\Mysql\Now
                        month: DoctrineExtensions\Query\Mysql\Month
                        monthname: DoctrineExtensions\Query\Mysql\MonthName
                        period_diff: DoctrineExtensions\Query\Mysql\PeriodDiff
                        second: DoctrineExtensions\Query\Mysql\Second
                        sectotime: DoctrineExtensions\Query\Mysql\SecToTime
                        strtodate: DoctrineExtensions\Query\Mysql\StrToDate
                        time: DoctrineExtensions\Query\Mysql\Time
                        timediff: DoctrineExtensions\Query\Mysql\TimeDiff
                        timestampadd: DoctrineExtensions\Query\Mysql\TimestampAdd
                        timestampdiff: DoctrineExtensions\Query\Mysql\TimestampDiff
                        timetosec: DoctrineExtensions\Query\Mysql\TimeToSec
                        week: DoctrineExtensions\Query\Mysql\Week
                        weekday: DoctrineExtensions\Query\Mysql\WeekDay
                        year: DoctrineExtensions\Query\Mysql\Year
                        yearmonth: DoctrineExtensions\Query\Mysql\YearMonth
                        yearweek: DoctrineExtensions\Query\Mysql\YearWeek
                        unix_timestamp: DoctrineExtensions\Query\Mysql\UnixTimestamp
                        utc_timestamp: DoctrineExtensions\Query\Mysql\UtcTimestamp
                        extract: DoctrineExtensions\Query\Mysql\Extract

                    numeric_functions:
                        acos: DoctrineExtensions\Query\Mysql\Acos
                        asin: DoctrineExtensions\Query\Mysql\Asin
                        atan2: DoctrineExtensions\Query\Mysql\Atan2
                        atan: DoctrineExtensions\Query\Mysql\Atan
                        bit_count: DoctrineExtensions\Query\Mysql\BitCount
                        bit_xor: DoctrineExtensions\Query\Mysql\BitXor
                        ceil: DoctrineExtensions\Query\Mysql\Ceil
                        cos: DoctrineExtensions\Query\Mysql\Cos
                        cot: DoctrineExtensions\Query\Mysql\Cot
                        degrees: DoctrineExtensions\Query\Mysql\Degrees
                        exp: DoctrineExtensions\Query\Mysql\Exp
                        floor: DoctrineExtensions\Query\Mysql\Floor
                        log: DoctrineExtensions\Query\Mysql\Log
                        log10: DoctrineExtensions\Query\Mysql\Log10
                        log2: DoctrineExtensions\Query\Mysql\Log2
                        pi: DoctrineExtensions\Query\Mysql\Pi
                        power: DoctrineExtensions\Query\Mysql\Power
                        quarter: DoctrineExtensions\Query\Mysql\Quarter
                        radians: DoctrineExtensions\Query\Mysql\Radians
                        rand: DoctrineExtensions\Query\Mysql\Rand
                        round: DoctrineExtensions\Query\Mysql\Round
                        stddev: DoctrineExtensions\Query\Mysql\StdDev
                        sin: DoctrineExtensions\Query\Mysql\Sin
                        std: DoctrineExtensions\Query\Mysql\Std
                        tan: DoctrineExtensions\Query\Mysql\Tan
                        variance: DoctrineExtensions\Query\Mysql\Variance

                    string_functions:
                        aes_decrypt: DoctrineExtensions\Query\Mysql\AesDecrypt
                        aes_encrypt: DoctrineExtensions\Query\Mysql\AesEncrypt
                        any_value: DoctrineExtensions\Query\Mysql\AnyValue
                        ascii: DoctrineExtensions\Query\Mysql\Ascii
                        binary: DoctrineExtensions\Query\Mysql\Binary
                        cast: DoctrineExtensions\Query\Mysql\Cast
                        char_length: DoctrineExtensions\Query\Mysql\CharLength
                        collate: DoctrineExtensions\Query\Mysql\Collate
                        concat_ws: DoctrineExtensions\Query\Mysql\ConcatWs
                        countif: DoctrineExtensions\Query\Mysql\CountIf
                        crc32: DoctrineExtensions\Query\Mysql\Crc32
                        degrees: DoctrineExtensions\Query\Mysql\Degrees
                        field: DoctrineExtensions\Query\Mysql\Field
                        find_in_set: DoctrineExtensions\Query\Mysql\FindInSet
                        greatest: DoctrineExtensions\Query\Mysql\Greatest
                        group_concat: DoctrineExtensions\Query\Mysql\GroupConcat
                        hex: DoctrineExtensions\Query\Mysql\Hex
                        ifelse: DoctrineExtensions\Query\Mysql\IfElse
                        ifnull: DoctrineExtensions\Query\Mysql\IfNull
                        inet_aton: DoctrineExtensions\Query\Mysql\InetAton
                        inet_ntoa: DoctrineExtensions\Query\Mysql\InetNtoa
                        inet6_aton: DoctrineExtensions\Query\Mysql\Inet6Aton
                        inet6_ntoa: DoctrineExtensions\Query\Mysql\Inet6Ntoa
                        instr: DoctrineExtensions\Query\Mysql\Instr
                        is_ipv4: DoctrineExtensions\Query\Mysql\IsIpv4
                        is_ipv4_compat: DoctrineExtensions\Query\Mysql\IsIpv4Compat
                        is_ipv4_mapped: DoctrineExtensions\Query\Mysql\IsIpv4Mapped
                        is_ipv6: DoctrineExtensions\Query\Mysql\IsIpv6
                        least: DoctrineExtensions\Query\Mysql\Least
                        lpad: DoctrineExtensions\Query\Mysql\Lpad
                        match: DoctrineExtensions\Query\Mysql\MatchAgainst
                        md5: DoctrineExtensions\Query\Mysql\Md5
                        nullif: DoctrineExtensions\Query\Mysql\NullIf
                        radians: DoctrineExtensions\Query\Mysql\Radians
                        regexp: DoctrineExtensions\Query\Mysql\Regexp
                        replace: DoctrineExtensions\Query\Mysql\Replace
                        rpad: DoctrineExtensions\Query\Mysql\Rpad
                        sha1: DoctrineExtensions\Query\Mysql\Sha1
                        sha2: DoctrineExtensions\Query\Mysql\Sha2
                        soundex: DoctrineExtensions\Query\Mysql\Soundex
                        str_to_date: DoctrineExtensions\Query\Mysql\StrToDate
                        substring_index: DoctrineExtensions\Query\Mysql\SubstringIndex
                        unhex: DoctrineExtensions\Query\Mysql\Unhex
                        uuid_short: DoctrineExtensions\Query\Mysql\UuidShort

        resolve_target_entities:
            CustomerBundle\PostalAddressSubjectInterface: CustomerBundle\Entity\PrivateIndividual

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool:
        type: file
        path: "%mailer_spool_path%"

fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: SecurityAppBundle\Entity\User
    service:
        mailer: app.mailerhtml.service #fos_user.mailer.twig_swift
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"
    change_password:
        form:
            type: me_user_change_password
    resetting:
        email:
           template: "email/password_resetting.email.html.twig"
        token_ttl: 7200 #Time to reset : 2h
        retry_ttl: 3600 #Time before submitting new request

sonata_media:
    # if you don't use default namespace configuration
    #class:
    #    media: MyVendor\MediaBundle\Entity\Media
    #    gallery: MyVendor\MediaBundle\Entity\Gallery
    #    gallery_has_media: MyVendor\MediaBundle\Entity\GalleryHasMedia
    db_driver: doctrine_orm # or doctrine_mongodb, doctrine_phpcr it is mandatory to choose one here
    default_context: default # you need to set a context
    contexts:
        default:  # the default context is mandatory
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file
                - sonata.media.provider.multiple_file
                - sonata.media.provider.vimeo
            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}
        business_case_media_context:  # to manage business case documents
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file
                - sonata.media.provider.multiple_file
                - sonata.media.provider.vimeo
            formats:
                xsmall: { width: 50, quality: 70 }
                small: { width: 100, quality: 70 }
                medium: { width: 300, quality: 70 }
                big:   { width: 500, quality: 70 }

    cdn:
        server:
            path: /uploads/media # http://media.sonata-project.org/

    filesystem:
        local:
            directory:  "%kernel.root_dir%/../web/uploads/media"
            create:     true