security_app_user:
    resource: "@SecurityAppBundle/Controller/UserController.php"
    type:     annotation

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin

security:
    resource: "@SecurityAppBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

jobstatus:
    resource: "@AppBundle/Resources/config/routing.yml"
#    prefix:   /admin