# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN:   [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
#        in_memory:
#            memory: ~
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:    ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                use_referer: true
                success_handler: redirect.after.login
                default_target_path: /
                target_path_parameter: redirect_url
            logout:
                path:   /logout
                target: /
            anonymous: ~


    access_control:
        - { requires_channel: https, path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { requires_channel: https, path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { requires_channel: https, path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { requires_channel: https, path: ^/admin, role: ROLE_ADMIN }
        - { requires_channel: https, path: ^/public, role: ROLE_USER }
        - { requires_channel: https, path: ^/, roles: ROLE_ACCESS_DENIED }
