# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    fos_user.registration.confirmation.template: '@@FOSUser/Registration/email.txt.twig'

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        #public: false

    # makes classes in src/AppBundle available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
#    AppBundle\:
#        resource: '../../src/AppBundle/*'
#        # you can exclude directories or files
#        # but if a service is unused, it's removed anyway
#        exclude: '../../src/AppBundle/{Entity,Repository,Tests}'


    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services

    #UPGRADE TO SF 3.4
#    AppBundle\Controller\:
#        resource: '../../src/AppBundle/Controller'
#        public: true
#        tags: ['controller.service_arguments']
    #UPGRADE TO SF 3.4
#    SecurityAppBundle\:
#        resource: '../../src/SecurityAppBundle/*'
#            # you can exclude directories or files
#            # but if a service is unused, it's removed anyway
#        exclude: '../../src/SecurityAppBundle/{Entity,Repository,Tests}'

    securityapp.form.type.role:
        class: SecurityAppBundle\Form\Type\RoleType
        arguments: ["@security.role_hierarchy"]

    redirect.after.login:
        class: SecurityAppBundle\Handlers\AfterLoginRedirection
        arguments: ['@router', '@security.authorization_checker']

    object.eximportdatas:
        class: AppBundle\Services\JsonExportImportData
        arguments: ["@doctrine.orm.entity_manager", "@jms_serializer"]

    business.case.internal_ref_generation:
        class: BusinessBundle\Service\InternalReferenceGeneratorSubscriber
        tags:
            - { name: doctrine.event_subscriber, connection: default }

#To update child entity instead of adding new one
    jms_serializer.object_constructor:
        alias: jms_serializer.doctrine_object_constructor
        public: false

    app.mailerhtml.service:
        class: AppBundle\Services\MailerHTMLService
        arguments:
            - "@mailer"
            - "@router"
            - "@templating"
            - "@twig"
            - { confirmation.template: '%fos_user.registration.confirmation.template%', resetting.template: '%fos_user.resetting.email.template%', kernel.root_dir: "%kernel.root_dir%", from_email: { confirmation: '%fos_user.registration.confirmation.from_email%', resetting: '%fos_user.resetting.email.from_email%' } }

#OVERRIDE : genemu bundle which called older form.renderer object
    genemu.twig.extension.form:
        class: AppBundle\Twig\Extension\GenemuFormExtension
        tags:
            - { name: twig.extension }
        arguments: ['@twig.form.renderer']

# NEW GRID COLUMN TYPE FOR DATATABLE - APY Bundle
    grid.column.country:
        class: AppBundle\Services\CountryGridColumn
        public: false
        tags:
          - { name: grid.column.extension }

    grid.column.color_tag:
        class: AppBundle\Services\ColorTagGridColumn
        public: false
        tags:
          - { name: grid.column.extension }

    grid.column.cvility:
        class: AppBundle\Services\CivilityGridColumn
        public: false
        tags:
            - { name: grid.column.extension }

# CUSTOM FORM TYPES EXTENSION, NOT OBJECT

    customerbundle.formtype.postaladdresstype:
        class: CustomerBundle\Form\PostalAddressType
        tags:
            - { name: form.type, alias: customerbundle_postaladdress }

    businessbundle.formtype.constructionsitepostaladdresstype:
        class: BusinessBundle\Form\ConstructionSitePostalAddressType
        tags:
            - { name: form.type, alias: businessbundle_postaladdress }

    appbundle.formtype.timepricetype:
        class: AppBundle\Form\TimePriceType
        tags:
            - { name: form.type, alias: appbundle_timeprice }

    appbundle.formtype.unittimepricetype:
        class: AppBundle\Form\UnitTimePriceType
        tags:
            - { name: form.type, alias: appbundle_unittimeprice }

    application.sonata.mediabundle.formtype.galleryhasmediacollection:
        class: Application\Sonata\MediaBundle\Form\Type\GalleryHasMediaCollectionType
        tags:
            - { name: form.type, alias: galleryHasMedias_collection_type }

    application.sonata.mediabundle.formtype.galleryhasmedianametype:
        class: Application\Sonata\MediaBundle\Form\Type\GalleryHasMediaNameTextType
        tags:
            - { name: form.type, alias: galleryHasMedias_name_text_type }

    business.formtype.gallery:
        class: BusinessBundle\Form\BusinessCaseGalleryType
        tags:
            - { name: form.type, alias: businesscase_gallery }

    application.sonata.mediabundle.form.galleryhasmediaform:
        class: Application\Sonata\MediaBundle\Form\GalleryHasMediaType
        tags:
            - { name: form.type, alias: galleryHasMedias_form }

    #TO FIX AN ERROR
    application.sonata.mediabundle.formtype.businesscasemediatype:
        class: Application\Sonata\MediaBundle\Form\BusinessCaseMediaType
        autowire: true
        autoconfigure: true
        arguments:
            - "@sonata.media.pool"
            - "Application\\Sonata\\MediaBundle\\Entity\\Media"
