<?php

namespace AppBundle\Entity\Repository;

/**
 * JobStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
