<?php

namespace AppBundle\Entity\Repository;

/**
 * TimePriceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TimePriceRepository extends \Doctrine\ORM\EntityRepository
{
}
