<?php

namespace AppBundle\Entity\Repository;

/**
 * UnitTimePriceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnitTimePriceRepository extends \Doctrine\ORM\EntityRepository
{
}
