equipment_index:
    path:     /
    defaults: { _controller: "AppBundle:Equipment:index" }
    methods:   [GET, POST]

equipment_show:
    path:     /{slug}/show
    defaults: { _controller: "AppBundle:Equipment:show" }
    methods:  GET

equipment_new:
    path:     /new
    defaults: { _controller: "AppBundle:Equipment:new" }
    methods:  [GET, POST]

equipment_edit:
    path:     /{slug}/edit
    defaults: { _controller: "AppBundle:Equipment:edit" }
    methods:  [GET, POST]

equipment_delete:
    path:     /{slug}/delete
    defaults: { _controller: "AppBundle:Equipment:delete" }
    methods:  DELETE

equipment_export:
    path: /export/{slug}
    defaults: { _controller: "AppBundle:Equipment:exportEquipment" }

equipment_export_all:
    path: /export
    defaults: { _controller: "AppBundle:Equipment:exportAllEquipment" }