jobstatus_index:
    path:     /
    defaults: { _controller: "AppBundle:JobStatus:index" }
    methods:   [GET, POST]

jobstatus_show:
    path:     /{slug}/show
    defaults: { _controller: "AppBundle:JobStatus:show" }
    methods:  GET

jobstatus_new:
    path:     /new
    defaults: { _controller: "AppBundle:JobStatus:new" }
    methods:  [GET, POST]

jobstatus_edit:
    path:     /{slug}/edit
    defaults: { _controller: "AppBundle:JobStatus:edit" }
    methods:  [GET, POST]

jobstatus_delete:
    path:     /{slug}/delete
    defaults: { _controller: "AppBundle:JobStatus:delete" }
    methods:  DELETE
    options:
        expose: true

jobstatus_export:
    path: /export/{slug}
    defaults: { _controller: "AppBundle:JobStatus:exportJobStatus" }

jobstatus_export_all:
    path: /export
    defaults: { _controller: "AppBundle:JobStatus:exportAllJobStatus" }