customer_article_index:
    path:     /
    defaults: { _controller: "AdminBundle:CustomerArticle:index" }
    methods: [GET, POST]

customer_article_show:
    path:     /{slug}/show
    defaults: { _controller: "AdminBundle:CustomerArticle:show" }
    methods:  GET

customer_article_new:
    path:     /new
    defaults: { _controller: "AdminBundle:CustomerArticle:new" }
    methods:  [GET, POST]
    host: "%casemanager_admin_url%"

customer_article_edit:
    path:     /{slug}/edit
    defaults: { _controller: "AdminBundle:CustomerArticle:edit" }
    methods:  [GET, POST]
    host: "%casemanager_admin_url%"

customer_article_delete:
    path:     /{slug}/delete
    defaults: { _controller: "AdminBundle:CustomerArticle:delete" }
    methods:  DELETE
    host: "%casemanager_admin_url%"
