customer_serial_index:
    path:     /
    defaults: { _controller: "AdminBundle:CustomerSerial:index" }
    methods: [GET, POST]

customer_serial_show:
    path:     /{slug}/show
    defaults: { _controller: "AdminBundle:CustomerSerial:show" }
    methods:  GET

customer_serial_new:
    path:     /new
    defaults: { _controller: "AdminBundle:CustomerSerial:new" }
    methods:  [GET, POST]
    host: "%casemanager_admin_url%"

customer_serial_edit:
    path:     /{slug}/edit
    defaults: { _controller: "AdminBundle:CustomerSerial:edit" }
    methods:  [GET, POST, PUT]
    host: "%casemanager_admin_url%"

customer_serial_delete:
    path:     /{slug}/delete
    defaults: { _controller: "AdminBundle:CustomerSerial:delete" }
    methods:  DELETE
    host: "%casemanager_admin_url%"

customer_serial_export:
    path: /export/{slug}
    defaults: { _controller: "AdminBundle:CustomerSerial:export" }

customer_serial_export_all:
    path: /export
    defaults: { _controller: "AdminBundle:CustomerSerial:exportAll" }