prestation_index:
    path:     /
    defaults: { _controller: "AdminBundle:Prestation:index" }
    methods:   [GET, POST]

prestation_show:
    path:     /{slug}/show
    defaults: { _controller: "AdminBundle:Prestation:show" }
    methods:  GET

prestation_new:
    path:     /new
    defaults: { _controller: "AdminBundle:Prestation:new" }
    methods:  [GET, POST]
    host: "%casemanager_admin_url%"

prestation_edit:
    path:     /{slug}/edit
    defaults: { _controller: "AdminBundle:Prestation:edit" }
    methods:  [GET, POST]
    host: "%casemanager_admin_url%"

prestation_delete:
    path:     /{slug}/delete
    defaults: { _controller: "AdminBundle:Prestation:delete" }
    methods:  DELETE
    options:
        expose: true
    host: "%casemanager_admin_url%"

prestation_export:
    path: /export/{slug}
    defaults: { _controller: "AdminBundle:Prestation:exportPrestation" }

prestation_export_all:
    path: /export
    defaults: { _controller: "AdminBundle:Prestation:exportAllPrestation" }