rate_index:
    path:     /
    defaults: { _controller: "AdminBundle:Rate:index" }
    methods:   [GET, POST]

rate_show:
    path:     /{slug}/show
    defaults: { _controller: "AdminBundle:Rate:show" }
    methods:  GET

rate_new:
    path:     /new
    defaults: { _controller: "AdminBundle:Rate:new" }
    methods:  [GET, POST]

rate_edit:
    path:     /{slug}/edit
    defaults: { _controller: "AdminBundle:Rate:edit" }
    methods:  [GET, POST]

rate_delete:
    path:     /{slug}/delete
    defaults: { _controller: "AdminBundle:Rate:delete" }
    methods:  DELETE
    options:
        expose: true

rate_export:
    path: /export/{slug}
    defaults: { _controller: "AdminBundle:Rate:exportRate" }

rate_export_all:
    path: /export
    defaults: { _controller: "AdminBundle:Rate:exportAllRate" }