unit_time_point_index:
    path:     /
    defaults: { _controller: "AdminBundle:UnitTimePoint:index" }
    methods:  [GET, POST]

unit_time_point_show:
    path:     /{slug}/show
    defaults: { _controller: "AdminBundle:UnitTimePoint:show" }
    methods:  GET

unit_time_point_new:
    path:     /new
    defaults: { _controller: "AdminBundle:UnitTimePoint:new" }
    methods:  [GET, POST]
    host: "%casemanager_admin_url%"

unit_time_point_edit:
    path:     /{slug}/edit
    defaults: { _controller: "AdminBundle:UnitTimePoint:edit" }
    methods:  [GET, POST]
    host: "%casemanager_admin_url%"

unit_time_point_delete:
    path:     /{slug}/delete
    defaults: { _controller: "AdminBundle:UnitTimePoint:delete" }
    methods:  DELETE
    host: "%casemanager_admin_url%"
