<?php

namespace CustomerBundle\Entity\Repository;

/**
 * CorporationSiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CorporationSiteRepository extends \Doctrine\ORM\EntityRepository
{
}
