<?php

namespace CustomerBundle\Entity\Repository;

/**
 * CorporationGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CorporationGroupRepository extends \Doctrine\ORM\EntityRepository
{

}
