<?php

namespace CustomerBundle\Entity\Repository;

/**
 * CorporationEmployeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CorporationEmployeeRepository extends \Doctrine\ORM\EntityRepository
{
}
