<?php

namespace CustomerBundle\Entity\Repository;

/**
 * CorporationJobStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CorporationJobStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
