<?php

namespace CustomerBundle\Entity\Repository;

/**
 * CustomerContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerContactRepository extends \Doctrine\ORM\EntityRepository
{
}
