<?php

namespace CustomerBundle\Entity\Repository;

use CustomerBundle\Entity\AbstractClass\Customer;
use Doctrine\ORM\EntityRepository;

/**
 * CustomerContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerContactRepository extends EntityRepository
{
    function getAllContactsByCustomerHTML(Customer $customer){
        $qb = $this->createQueryBuilder("ca");
        $qb
            ->join("ca.customer", "c", "WITH", "c.id = :customerID")
//            ->where("ca.customer", $customerID)
            ->orderBy("ca.lastName", "ASC");

        $qb->setParameter("customerID", $customer->getId());

        return $qb;
    }
}
