<?php

namespace CustomerBundle\Entity\Repository;

/**
 * OtherCustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OtherCustomerRepository extends \Doctrine\ORM\EntityRepository
{
}
