<?php

namespace CustomerBundle\Entity\Repository;

/**
 * PostalAddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostalAddressRepository extends \Doctrine\ORM\EntityRepository
{
}
