<?php

namespace CustomerBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PrivateIndividualRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrivateIndividualRepository extends EntityRepository
{
}
