<?php

namespace CustomerBundle\Entity\Repository;

/**
 * TownShipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TownShipRepository extends \Doctrine\ORM\EntityRepository
{
}
