<?php

namespace AdminBundle\Entity\Repository;

/**
 * ConstructionSiteTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConstructionSiteTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
