<?php

namespace AdminBundle\Entity\Repository;

/**
 * CustomerChapterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerChapterRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLastCreatedPrestation(){
        $qb = $this->createQueryBuilder("p");
        $qb
            ->where("p.internalReference IS NOT NULL")
            ->orderBy("p.created", "DESC");

        $qb->setMaxResults(1);

        return $qb->getQuery()->getOneOrNullResult();
    }
}
