<?php

namespace AdminBundle\Entity\Repository;

/**
 * WorkSiteTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkSiteTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
