customer_corporation_group:
    resource: "@CustomerBundle/Resources/config/routing/corporationgroup.yml"
    prefix:   /corporation-group

customer_corporation_site:
    resource: "@CustomerBundle/Resources/config/routing/corporationsite.yml"
    prefix:   /corporation-site

customer_corporation_employee:
    resource: "@CustomerBundle/Resources/config/routing/corporationemployee.yml"
    prefix:   /corporation-employee

customer_corporation_job_status:
    resource: "@CustomerBundle/Resources/config/routing/corporationjobstatus.yml"
    prefix:   /corporation-job-status


customer_homepage:
    path: /
    defaults: { _controller: CustomerBundle:Default:index }
