customer_corporation_group:
    resource: "@CustomerBundle/Resources/config/routing/corporationgroup.yml"
    prefix:   /corporation-group

customer_corporation_site:
    resource: "@CustomerBundle/Resources/config/routing/corporationsite.yml"
    prefix:   /corporation-site

customer_customer_contact:
    resource: "@CustomerBundle/Resources/config/routing/customercontact.yml"
    prefix:   /corporation-employee

customer_corporation_job_status:
    resource: "@CustomerBundle/Resources/config/routing/corporationjobstatus.yml"
    prefix:   /corporation-job-status

customer_private_individual:
    resource: "@CustomerBundle/Resources/config/routing/privateindividual.yml"
    prefix:   /private-individual

customer_township:
    resource: "@CustomerBundle/Resources/config/routing/township.yml"
    prefix:   /township

customer_other:
    resource: "@CustomerBundle/Resources/config/routing/othercustomer.yml"
    prefix:   /other-customer

customer_homepage:
    path: /
    defaults: { _controller: CustomerBundle:Default:index }
