corporation_group_index:
    path:     /
    defaults: { _controller: "CustomerBundle:CorporationGroup:index" }
    methods:  [GET, POST]

corporation_group_show:
    path:     /{slug}/show
    defaults: { _controller: "CustomerBundle:CorporationGroup:show" }
    methods:  GET

corporation_group_new:
    path:     /new
    defaults: { _controller: "CustomerBundle:CorporationGroup:new" }
    methods:  [GET, POST]

corporation_group_edit:
    path:     /{slug}/edit
    defaults: { _controller: "CustomerBundle:CorporationGroup:edit" }
    methods:  [GET, POST]

corporation_group_delete:
    path:     /{slug}/delete
    defaults: { _controller: "CustomerBundle:CorporationGroup:delete" }
    methods:  DELETE

corporation_group_export:
    path: /export/{slug}
    defaults: { _controller: "CustomerBundle:CorporationGroup:exportCorporationGroup" }

corporation_group_export_all:
    path: /export
    defaults: { _controller: "CustomerBundle:CorporationGroup:exportAllCorporationGroup" }