corporation_site_index:
    path:     /
    defaults: { _controller: "CustomerBundle:CorporationSite:index" }
    methods:  [GET, POST]

corporation_site_show:
    path:     /{slug}/show
    defaults: { _controller: "CustomerBundle:CorporationSite:show" }
    methods:  GET

corporation_site_new:
    path:     /new/{slugCorpGroup}
    defaults: { _controller: "CustomerBundle:CorporationSite:new", slugCorpGroup: ~ }
    methods:  [GET, POST]

corporation_site_edit:
    path:     /{slug}/edit
    defaults: { _controller: "CustomerBundle:CorporationSite:edit" }
    methods:  [GET, POST]

corporation_site_delete:
    path:     /{slug}/delete
    defaults: { _controller: "CustomerBundle:CorporationSite:delete" }
    methods:  DELETE
    options:
        expose: true

corporation_site_export:
    path: /export/{slug}
    defaults: { _controller: "CustomerBundle:CorporationSite:exportCorporationSite" }

corporation_site_export_all:
    path: /export
    defaults: { _controller: "CustomerBundle:CorporationSite:exportAllCorporationSite" }

corporation_site_get_children:
    path:     /{id}/children/{childElement}
    defaults: { _controller: "CustomerBundle:CorporationSite:getChildFromParent" }
    methods:  POST
    options:
        expose: true