corporation_employee_index:
    path:     /
    defaults: { _controller: "CustomerBundle:CorporationEmployee:index" }
    methods:  [GET, POST]

corporation_employee_show:
    path:     /{slug}/show
    defaults: { _controller: "CustomerBundle:CorporationEmployee:show" }
    methods:  GET

corporation_employee_new:
    path:     /new/{slugCorpSite}
    defaults: { _controller: "CustomerBundle:CorporationEmployee:new", slugCorpSite: ~}
    methods:  [GET, POST]

corporation_employee_edit:
    path:     /{slug}/edit
    defaults: { _controller: "CustomerBundle:CorporationEmployee:edit" }
    methods:  [GET, POST]

corporation_employee_delete:
    path:     /{slug}/delete
    defaults: { _controller: "CustomerBundle:CorporationEmployee:delete" }
    methods:  DELETE
    
corporation_employee_export:
    path: /export/{slug}
    defaults: { _controller: "CustomerBundle:CorporationEmployee:exportCorporationEmployee" }

corporation_employee_export_all:
    path: /export
    defaults: { _controller: "CustomerBundle:CorporationEmployee:exportAllCorporationEmployee" }