corporation_jobstatus_index:
    path:     /
    defaults: { _controller: "CustomerBundle:CorporationJobStatus:index" }
    methods:  [GET, POST]

corporation_jobstatus_show:
    path:     /{slug}/show
    defaults: { _controller: "CustomerBundle:CorporationJobStatus:show" }
    methods:  GET

corporation_jobstatus_new:
    path:     /new
    defaults: { _controller: "CustomerBundle:CorporationJobStatus:new" }
    methods:  [GET, POST]

corporation_jobstatus_edit:
    path:     /{slug}/edit
    defaults: { _controller: "CustomerBundle:CorporationJobStatus:edit" }
    methods:  [GET, POST]

corporation_jobstatus_delete:
    path:     /{slug}/delete
    defaults: { _controller: "CustomerBundle:CorporationJobStatus:delete" }
    methods:  DELETE
    options:
        expose: true

corporation_jobstatus_export:
    path: /export/{slug}
    defaults: { _controller: "CustomerBundle:CorporationJobStatus:exportCorporationJobStatus" }

corporation_jobstatus_export_all:
    path: /export
    defaults: { _controller: "CustomerBundle:CorporationJobStatus:exportAllCorporationJobStatus" }

corporation_jobstatus_get_children:
    path:     /{id}/children/{childElement}
    defaults: { _controller: "CustomerBundle:CorporationJobStatus:getChildFromParent" }
    methods:  POST
    options:
        expose: true