corporation_site_index:
    path:     /
    defaults: { _controller: "CustomerBundle:CorporationSite:index" }
    methods:  GET

corporation_site_show:
    path:     /{slug}/show
    defaults: { _controller: "CustomerBundle:CorporationSite:show" }
    methods:  GET

corporation_site_new:
    path:     /new
    defaults: { _controller: "CustomerBundle:CorporationSite:new" }
    methods:  [GET, POST]

corporation_site_edit:
    path:     /{slug}/edit
    defaults: { _controller: "CustomerBundle:CorporationSite:edit" }
    methods:  [GET, POST]

corporation_site_delete:
    path:     /{slug}/delete
    defaults: { _controller: "CustomerBundle:CorporationSite:delete" }
    methods:  DELETE

corporation_site_export:
    path: /export/{slug}
    defaults: { _controller: "CustomerBundle:CorporationSite:exportCorporationSite" }

corporation_site_export_all:
    path: /export
    defaults: { _controller: "CustomerBundle:CorporationSite:exportAllCorporationSite" }