private_individual_index:
    path:     /
    defaults: { _controller: "CustomerBundle:PrivateIndividual:index" }
    methods:  [GET, POST]

private_individual_show:
    path:     /{slug}/show
    defaults: { _controller: "CustomerBundle:PrivateIndividual:show" }
    methods:  GET

private_individual_new:
    path:     /new
    defaults: { _controller: "CustomerBundle:PrivateIndividual:new" }
    methods:  [GET, POST]

private_individual_edit:
    path:     /{slug}/edit
    defaults: { _controller: "CustomerBundle:PrivateIndividual:edit" }
    methods:  [GET, POST]

private_individual_delete:
    path:     /{slug}/delete
    defaults: { _controller: "CustomerBundle:PrivateIndividual:delete" }
    methods:  DELETE
    options:
        expose: true

private_individual_export:
    path: /export/{slug}
    defaults: { _controller: "CustomerBundle:PrivateIndividual:exportPrivateIndividual" }

private_individual_export_all:
    path: /export