<?php

namespace BusinessBundle\Repository;

/**
 * BusinessCaseGalleryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusinessCaseGalleryRepository extends \Doctrine\ORM\EntityRepository
{
}
