business_document_type_index:
    path:     /
    defaults: { _controller: "BusinessBundle:DocumentType:index" }
    methods:  GET

business_document_type_show:
    path:     /{slug}/show
    defaults: { _controller: "BusinessBundle:DocumentType:show" }
    methods:  GET

business_document_type_new:
    path:     /new
    defaults: { _controller: "BusinessBundle:DocumentType:new" }
    methods:  [GET, POST]
    host: "%casemanager_admin_url%"

business_document_type_edit:
    path:     /{slug}/edit
    defaults: { _controller: "BusinessBundle:DocumentType:edit" }
    methods:  [GET, POST]
    host: "%casemanager_admin_url%"

business_document_type_delete:
    path:     /{slug}/delete
    defaults: { _controller: "BusinessBundle:DocumentType:delete" }
    methods:  DELETE
    host: "%casemanager_admin_url%"

business_document_type_export:
    path: /export/{slug}
    defaults: { _controller: "BusinessBundle:DocumentType:exportDocumentType" }

business_document_type_export_all:
    path: /export