business_work_site_type_index:
    path:     /
    defaults: { _controller: "BusinessBundle:WorkSite:index" }
    methods:  GET

business_work_site_type_show:
    path:     /{slug}/show
    defaults: { _controller: "BusinessBundle:WorkSite:show" }
    methods:  GET


business_work_site_type_new:
    path:     /new
    defaults: { _controller: "BusinessBundle:WorkSite:new" }
    methods:  [GET, POST]
    host: "%casemanager_admin_url%"

business_work_site_type_edit:
    path:     /{slug}/edit
    defaults: { _controller: "BusinessBundle:WorkSite:edit" }
    methods:  [GET, POST]
    host: "%casemanager_admin_url%"

business_work_site_type_delete:
    path:     /{slug}/delete
    defaults: { _controller: "BusinessBundle:WorkSite:delete" }
    methods:  DELETE
    host: "%casemanager_admin_url%"

business_work_site_type_export:
    path: /export/{slug}
    defaults: { _controller: "BusinessBundle:WorkSite:exportWorkSite" }

business_work_site_type_export_all:
    path: /export