<?php

namespace BusinessBundle\Entity\Repository;

/**
 * BusinessCaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusinessCaseRepository extends \Doctrine\ORM\EntityRepository
{
}
