<?php

namespace BusinessBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ConstructionSitePostalAddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConstructionSitePostalAddressRepository extends EntityRepository
{
}
