<?php

namespace BusinessBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * WorkSiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkSiteRepository extends EntityRepository
{
}
