<?php
/**
 * Created by PhpStorm.
 * User: DG713C7N
 * Date: 28/01/2019
 * Time: 11:54
 */

namespace AppBundle\Services;


use APY\DataGridBundle\Grid\Column\TextColumn;

class CivilityGridColumn extends TextColumn
{
    protected $translateCivility;

    public function __initialize(array $params)
    {
        parent::__initialize($params); // TODO: Change the autogenerated stub
        $this->setTranslateCivility($this->getParam("translateCivility"));
    }

    public function getType()
    {
        return "civility";
    }

    /**
     * @return mixed
     */
    public function getTranslateCivility()
    {
        return $this->translateCivility;
    }

    /**
     * @param mixed $translateCivility
     */
    public function setTranslateCivility($translateCivility)
    {
        $this->translateCivility = $translateCivility;
    }
}